development:
  adapter: mysql2
  database: changjiang_dev
  encoding: utf8
  username: root
  host: 127.0.0.1
  password: '13636632007'
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  encoding: utf8
  database: changjiang_test
  username: root
  host: 127.0.0.1
  password: '13636632007'
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: changjiang
  encoding: utf8
  username: root
  host: 127.0.0.1
  password: '13636632007'
  pool: 5
  timeout: 5000
